export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCEEDED = 'FETCH_MOVIES_SUCCEEDED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCEEDED = 'FETCH_COMMENTS_SUCCEEDED';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';
export const EDIT_COMMENT_TEXT = 'EDIT_COMMENT_TEXT';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCEEDED = 'ADD_COMMENT_SUCCEEDED';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';