# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'turtle_movie_chat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for turtle_movie_chat

  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'

end
